package com.anuj.notificationfirewall.ai.ask

sealed interface SqlVerdict {
    data class Allowed(val sql: String) : SqlVerdict
    data class Rejected(val reason: String) : SqlVerdict
}

/**
 * Gate between a model-authored string and the user's database.
 *
 * The posture is allow-list, not deny-list: the statement must be a single
 * SELECT, over four named tables, with a bounded LIMIT, and — unless the user
 * opted in for this query — mentioning neither content column anywhere, not
 * even in a WHERE clause, since a filter on text leaks it one row at a time.
 * Anything not positively recognised is rejected.
 *
 * A deny-list would be the wrong shape here. The input is generated by a model
 * that can be steered by the contents of notifications it has read, so the
 * question is not "have I thought of every bad statement" but "have I permitted
 * only the good ones".
 *
 * The content-leak guard is not a bare `contains("*")`: that would also reject
 * `COUNT(*)`, which is a legitimate aggregate. Instead it specifically rejects
 * a bare or qualified star *projection* (`SELECT *`, `SELECT  *`, `SELECT\n*`,
 * `SELECT n.*`, including one among several projected columns) and rejects
 * whole-word references to the `title`/`text` columns anywhere in the
 * statement — while leaving `COUNT(*)`, `COUNT( * )`, and identifiers that
 * merely contain "title" or "text" as a substring (e.g. `titles`, or a string
 * literal like `'com.title.app'`) untouched.
 */
object SqlValidator {

    const val MAX_LIMIT = 500

    private val KNOWN_TABLES = setOf("notifications", "verdict_cache", "sender_bias", "overrides")
    private val CONTENT_COLUMNS = setOf("title", "text")

    private val FORBIDDEN = listOf(
        "insert", "update", "delete", "drop", "alter", "create", "replace",
        "pragma", "attach", "detach", "vacuum", "reindex", "trigger",
        "sqlite_master", "sqlite_temp_master", "load_extension",
    )

    private val FROM_OR_JOIN = Regex("""\b(?:from|join)\s+([a-z_][a-z0-9_]*)""", RegexOption.IGNORE_CASE)
    private val FROM_KEYWORD = Regex("""\bfrom\b""", RegexOption.IGNORE_CASE)
    private val CLAUSE_STOP_WORDS = setOf("where", "group", "order", "limit")
    private val LIMIT = Regex("""\blimit\s+(\d+)""", RegexOption.IGNORE_CASE)
    private val FENCE = Regex("""^```(?:sql)?\s*|\s*```$""", RegexOption.IGNORE_CASE)

    // Quoted string literals can contain arbitrary text ('com.title.app') that
    // must not be mistaken for a keyword or column reference. Blank them out
    // (preserving length, so other offsets/regexes are unaffected) before any
    // keyword or column-name check.
    private val STRING_LITERAL = Regex("""'[^']*'""")
    private fun maskLiterals(s: String) = STRING_LITERAL.replace(s) { " ".repeat(it.value.length) }

    // `FROM_OR_JOIN` only captures the single identifier right after `from`/
    // `join`, so `FROM notifications, evil_table` would smuggle a second,
    // unchecked table past it via the old-style comma join. Comma joins are
    // simply not supported: if a top-level comma (i.e. not inside a
    // parenthesised subquery or IN-list) appears anywhere between `from` and
    // the next clause (where/group/order/limit) or the end of the statement,
    // reject outright rather than risk missing a table.
    private fun hasTopLevelCommaInFromClause(text: String): Boolean {
        val fromEnd = FROM_KEYWORD.find(text)?.range?.last?.plus(1) ?: return false
        var depth = 0
        var i = fromEnd
        while (i < text.length) {
            val c = text[i]
            when (c) {
                '(' -> depth++
                ')' -> depth--
            }
            if (depth <= 0) {
                if (c == ',') return true
                if (c.isLetter() && (i == 0 || !text[i - 1].isLetterOrDigit() && text[i - 1] != '_')) {
                    val word = CLAUSE_STOP_WORDS.firstOrNull { stop ->
                        text.regionMatches(i, stop, 0, stop.length) &&
                            (i + stop.length == text.length || !text[i + stop.length].isLetterOrDigit() && text[i + stop.length] != '_')
                    }
                    if (word != null) return false
                }
            }
            i++
        }
        return false
    }

    // The projection is everything between the leading SELECT and the first
    // top-level FROM. A star there — bare or qualified (`t.*`), alone or
    // alongside other columns — would expand to include title/text.
    private val PROJECTION = Regex("""^select\s+(.*?)\s+from\b""", RegexOption.DOT_MATCHES_ALL)
    private val STAR_PROJECTION = Regex("""(?:^|,)\s*(?:[a-z_][a-z0-9_]*\.)?\*\s*(?:,|$)""")

    fun validate(raw: String, allowContent: Boolean): SqlVerdict {
        val sql = raw.trim().replace(FENCE, "").trim().removeSuffix(";").trim()

        if (sql.isEmpty()) return SqlVerdict.Rejected("Empty statement")

        // Comments can hide a second statement from a naive split, and nothing
        // legitimate here needs them.
        if (sql.contains("--") || sql.contains("/*")) {
            return SqlVerdict.Rejected("Comments are not permitted")
        }
        if (sql.contains(";")) {
            return SqlVerdict.Rejected("Only a single statement is permitted")
        }

        val lower = sql.lowercase()
        val masked = maskLiterals(lower)

        if (!lower.startsWith("select ")) {
            return SqlVerdict.Rejected("Only SELECT statements are permitted")
        }
        FORBIDDEN.firstOrNull { Regex("""\b${Regex.escape(it)}\b""").containsMatchIn(masked) }
            ?.let { return SqlVerdict.Rejected("Forbidden keyword: $it") }

        if (hasTopLevelCommaInFromClause(masked)) {
            return SqlVerdict.Rejected("Comma joins are not supported; use JOIN")
        }

        val tables = FROM_OR_JOIN.findAll(masked).map { it.groupValues[1] }.toSet()
        if (tables.isEmpty()) return SqlVerdict.Rejected("No table referenced")
        (tables - KNOWN_TABLES).firstOrNull()
            ?.let { return SqlVerdict.Rejected("Unknown table: $it") }

        if (!allowContent) {
            val projection = PROJECTION.find(masked)?.groupValues?.get(1).orEmpty()
            if (STAR_PROJECTION.containsMatchIn(projection)) {
                return SqlVerdict.Rejected("SELECT * would expose notification content")
            }
            CONTENT_COLUMNS.firstOrNull { Regex("""\b$it\b""").containsMatchIn(masked) }
                ?.let { return SqlVerdict.Rejected("Column '$it' holds notification content") }
        }

        val limit = LIMIT.find(lower)?.groupValues?.get(1)?.toIntOrNull()
            ?: return SqlVerdict.Rejected("A LIMIT is required")
        if (limit > MAX_LIMIT) return SqlVerdict.Rejected("LIMIT must be at most $MAX_LIMIT")

        return SqlVerdict.Allowed(sql)
    }
}
