package com.anuj.notificationfirewall.ai.ask

sealed interface SqlVerdict {
    data class Allowed(val sql: String) : SqlVerdict
    data class Rejected(val reason: String) : SqlVerdict
}

/**
 * Gate between a model-authored string and the user's database.
 *
 * The posture is allow-list, not deny-list: the statement must be a single
 * SELECT, over four named tables, with a bounded LIMIT, and — unless the user
 * opted in for this query — mentioning neither content column anywhere, not
 * even in a WHERE clause, since a filter on text leaks it one row at a time.
 * Anything not positively recognised is rejected.
 *
 * A deny-list would be the wrong shape here. The input is generated by a model
 * that can be steered by the contents of notifications it has read, so the
 * question is not "have I thought of every bad statement" but "have I permitted
 * only the good ones".
 *
 * The content-leak guard is not a bare `contains("*")`: that would also reject
 * `COUNT(*)`, which is a legitimate aggregate. Instead it specifically rejects
 * a bare or qualified star *projection* (`SELECT *`, `SELECT  *`, `SELECT\n*`,
 * `SELECT n.*`, `SELECT *FROM` with no separating space, including one among
 * several projected columns) and rejects whole-word references to the
 * `title`/`text` columns anywhere in the statement — while leaving
 * `COUNT(*)`, `COUNT( * )`, and identifiers that merely contain "title" or
 * "text" as a substring (e.g. `titles`, or a string literal like
 * `'com.title.app'`) untouched.
 *
 * Double quotes, backticks and square brackets are rejected outright rather
 * than masked like single-quoted literals: SQLite accepts any of them as
 * identifier quoting, and an identifier can contain almost anything —
 * including a `(` or `,` that would otherwise defeat the paren-depth and
 * comma-join checks below. Nothing this feature's schema needs requires
 * quoting an identifier, so the whole class is refused up front.
 */
object SqlValidator {

    const val MAX_LIMIT = 500

    private val KNOWN_TABLES = setOf("notifications", "verdict_cache", "sender_bias", "overrides")
    private val CONTENT_COLUMNS = setOf("title", "text")

    private val FORBIDDEN = listOf(
        "insert", "update", "delete", "drop", "alter", "create", "replace",
        "pragma", "attach", "detach", "vacuum", "reindex", "trigger",
        "sqlite_master", "sqlite_temp_master", "load_extension",
    )
    private val FORBIDDEN_PATTERNS = FORBIDDEN.map { it to Regex("""\b${Regex.escape(it)}\b""") }

    private val QUOTE_CHARS = charArrayOf('"', '`', '[', ']')

    private val SELECT_START = Regex("""^select\b""", RegexOption.IGNORE_CASE)
    private val FROM_OR_JOIN = Regex("""\b(?:from|join)\s+([a-z_][a-z0-9_]*)""", RegexOption.IGNORE_CASE)
    private val FROM_KEYWORD = Regex("""\bfrom\b""", RegexOption.IGNORE_CASE)
    private val CLAUSE_STOP_WORDS = setOf("where", "group", "order", "limit")
    private val FENCE = Regex("""^```(?:sql)?\s*|\s*```$""", RegexOption.IGNORE_CASE)

    // Exactly one LIMIT is tolerated, and it must be the final clause of the
    // statement: `LIMIT <n>` optionally followed by `OFFSET <n>`. Anchoring to
    // the end of the string rules out `LIMIT 1, 100000` (SQLite's
    // offset,count form — the number that actually bounds the result set is
    // the *second* one) and `LIMIT 5*1000` (an expression, not a bare
    // integer), both of which a non-anchored "first digits after limit"
    // capture would misread as the small, safe-looking number.
    private val LIMIT_KEYWORD = Regex("""\blimit\b""", RegexOption.IGNORE_CASE)
    private val LIMIT_CLAUSE = Regex(
        """\blimit\s+(\d+)\s*(?:offset\s+\d+\s*)?$""",
        setOf(RegexOption.IGNORE_CASE),
    )

    // Quoted string literals can contain arbitrary text ('com.title.app') that
    // must not be mistaken for a keyword or column reference. Blank them out
    // (preserving length, so other offsets/regexes are unaffected) before any
    // keyword or column-name check.
    private val STRING_LITERAL = Regex("""'[^']*'""")
    private fun maskLiterals(s: String) = STRING_LITERAL.replace(s) { " ".repeat(it.value.length) }

    // `FROM_OR_JOIN` only captures the single identifier right after `from`/
    // `join`, so `FROM notifications, evil_table` would smuggle a second,
    // unchecked table past it via the old-style comma join. Comma joins are
    // simply not supported: if a top-level comma (i.e. not inside a
    // parenthesised subquery or IN-list) appears anywhere between `from` and
    // the next clause (where/group/order/limit) or the end of the statement,
    // reject outright rather than risk missing a table.
    private fun hasTopLevelCommaInFromClause(text: String): Boolean {
        val fromEnd = FROM_KEYWORD.find(text)?.range?.last?.plus(1) ?: return false
        var depth = 0
        var i = fromEnd
        while (i < text.length) {
            val c = text[i]
            when (c) {
                '(' -> depth++
                ')' -> depth--
            }
            if (depth == 0) {
                if (c == ',') return true
                if (c.isLetter() && (i == 0 || !text[i - 1].isLetterOrDigit() && text[i - 1] != '_')) {
                    val word = CLAUSE_STOP_WORDS.firstOrNull { stop ->
                        text.regionMatches(i, stop, 0, stop.length) &&
                            (i + stop.length == text.length || !text[i + stop.length].isLetterOrDigit() && text[i + stop.length] != '_')
                    }
                    if (word != null) return false
                }
            }
            i++
        }
        return false
    }

    private fun hasUnbalancedParens(text: String): Boolean {
        var depth = 0
        for (c in text) {
            when (c) {
                '(' -> depth++
                ')' -> {
                    depth--
                    if (depth < 0) return true
                }
            }
        }
        return depth != 0
    }

    // The projection is everything between the leading SELECT and the first
    // top-level FROM. A star there — bare or qualified (`t.*`), alone or
    // alongside other columns — would expand to include title/text. The
    // boundary is `\b`, not `\s+`: `SELECT *FROM notifications` has no space
    // between the star and FROM, and a whitespace-requiring boundary would
    // fail to match at all, silently falling back to an empty projection and
    // letting the star through unchecked.
    private val PROJECTION = Regex("""^select\b(.*?)\bfrom\b""", RegexOption.DOT_MATCHES_ALL)
    private val STAR_PROJECTION = Regex("""(?:^|,)\s*(?:[a-z_][a-z0-9_]*\.)?\*\s*(?:,|$)""")

    fun validate(raw: String, allowContent: Boolean): SqlVerdict {
        val sql = raw.trim().replace(FENCE, "").trim().removeSuffix(";").trim()

        if (sql.isEmpty()) return SqlVerdict.Rejected("Empty statement")

        // Comments can hide a second statement from a naive split, and nothing
        // legitimate here needs them.
        if (sql.contains("--") || sql.contains("/*")) {
            return SqlVerdict.Rejected("Comments are not permitted")
        }
        if (sql.contains(";")) {
            return SqlVerdict.Rejected("Only a single statement is permitted")
        }
        if (sql.any { it in QUOTE_CHARS }) {
            return SqlVerdict.Rejected("Quoted or bracketed identifiers (\", `, [, ]) are not permitted")
        }

        val lower = sql.lowercase()
        val masked = maskLiterals(lower)

        if (hasUnbalancedParens(masked)) {
            return SqlVerdict.Rejected("Unbalanced parentheses")
        }

        if (!SELECT_START.containsMatchIn(lower)) {
            return SqlVerdict.Rejected("Only SELECT statements are permitted")
        }
        FORBIDDEN_PATTERNS.firstOrNull { (_, pattern) -> pattern.containsMatchIn(masked) }
            ?.let { (word, _) -> return SqlVerdict.Rejected("Forbidden keyword: $word") }

        if (hasTopLevelCommaInFromClause(masked)) {
            return SqlVerdict.Rejected("Comma joins are not supported; use JOIN")
        }

        val tables = FROM_OR_JOIN.findAll(masked).map { it.groupValues[1] }.toSet()
        if (tables.isEmpty()) return SqlVerdict.Rejected("No table referenced")
        (tables - KNOWN_TABLES).firstOrNull()
            ?.let { return SqlVerdict.Rejected("Unknown table: $it") }

        if (!allowContent) {
            val projectionMatch = PROJECTION.find(masked)
                ?: return SqlVerdict.Rejected("Could not determine the SELECT projection")
            val projection = projectionMatch.groupValues[1]
            if (STAR_PROJECTION.containsMatchIn(projection)) {
                return SqlVerdict.Rejected("SELECT * would expose notification content")
            }
            CONTENT_COLUMNS.firstOrNull { Regex("""\b$it\b""").containsMatchIn(masked) }
                ?.let { return SqlVerdict.Rejected("Column '$it' holds notification content") }
        }

        if (LIMIT_KEYWORD.findAll(masked).count() != 1) {
            return SqlVerdict.Rejected("Exactly one LIMIT clause is required")
        }
        val limitMatch = LIMIT_CLAUSE.find(masked)
            ?: return SqlVerdict.Rejected("LIMIT must be the final clause, as LIMIT <n> optionally followed by OFFSET <n>")
        val limit = limitMatch.groupValues[1].toIntOrNull()
            ?: return SqlVerdict.Rejected("A LIMIT is required")
        if (limit > MAX_LIMIT) return SqlVerdict.Rejected("LIMIT must be at most $MAX_LIMIT")

        return SqlVerdict.Allowed(sql)
    }
}
