package com.anuj.notificationfirewall.ai.ask

sealed interface SqlVerdict {
    data class Allowed(val sql: String) : SqlVerdict
    data class Rejected(val reason: String) : SqlVerdict
}

/**
 * Gate between a model-authored string and the user's database.
 *
 * The posture is allow-list, not deny-list: the statement must be a single
 * SELECT, over four named tables, with a bounded LIMIT, and — unless the user
 * opted in for this query — mentioning neither content column anywhere, not
 * even in a WHERE clause, since a filter on text leaks it one row at a time.
 * Anything not positively recognised is rejected.
 *
 * A deny-list would be the wrong shape here. The input is generated by a model
 * that can be steered by the contents of notifications it has read, so the
 * question is not "have I thought of every bad statement" but "have I permitted
 * only the good ones".
 *
 * Double quotes, backticks and square brackets are rejected outright rather
 * than masked like single-quoted literals: SQLite accepts any of them as
 * identifier quoting, and an identifier can contain almost anything —
 * including a `(` or `,` that would defeat the paren-depth and comma-join
 * checks below. Nothing this feature's schema needs requires quoting an
 * identifier, so the whole class is refused up front.
 *
 * The star-projection check reads the output of a single top-level parse
 * ([findTopLevelProjection]) instead of re-deriving "where does the real
 * projection end" with its own regex — two separate leaks in earlier
 * revisions of this file traced back to exactly that kind of re-derivation
 * going wrong (a whitespace assumption between the projection and FROM, and
 * a first-`from`-anywhere scan that landed inside a subquery's parentheses
 * and truncated the projection before the real star was ever seen).
 *
 * The comma-join check ([hasCommaInAnyFromClause]) deliberately does *not*
 * share that "top level" notion. A comma join can hide inside any `FROM`
 * anywhere in the statement — the outermost one, or one nested inside a
 * WHERE/HAVING subquery, or one nested inside a subquery embedded in the
 * projection — and each occurrence needs the same check applied to its own
 * local table clause, independent of how deeply it's nested. Tying comma
 * detection to a single "the" top-level FROM (as an earlier revision did)
 * is what let a comma join inside a projection subquery defeat the guard
 * entirely, since the scanner started counting parenthesis depth from the
 * position of first `from` found — which could itself be inside a subquery
 * — rather than from each occurrence's own start.
 */
object SqlValidator {

    const val MAX_LIMIT = 500

    private val KNOWN_TABLES = setOf("notifications", "verdict_cache", "sender_bias", "overrides")

    /**
     * Content is defined by provenance, not by column name.
     *
     * `senderKey` is not a derived identifier: [com.anuj.notificationfirewall.service.NotificationMapper]
     * assigns `senderKey = title`, verbatim, and `title` is
     * `EXTRA_TITLE` — for an e-mail client, often the subject line.
     * `contentShape` is `MD5(normalize("$title $text"))`, and normalisation
     * removes nothing lexical, so it is a recoverable digest of the message.
     * Both therefore sit behind the same per-question opt-in as `title` and
     * `text` themselves.
     *
     * The alternative reading — that content means the two columns we happened
     * to name "title" and "text" — would make the privacy boundary an accident
     * of naming, and the retention job already contradicts it: `purgeTextBefore`
     * nulls `title` and `text` while leaving `senderKey` holding the same string,
     * so a name-based rule would let Ask send values the app already promised to
     * purge.
     *
     * `overrides.label` is here for the same reason and was found by applying
     * the rule rather than reading a list: `InboxViewModel.addOverride` passes
     * `label = row.sender ?: row.appLabel`, and `row.sender` is `senderKey`,
     * which is the title. A swipe-created override therefore stores a raw
     * title in `label`. (`appLabel` is a different column and is not matched
     * here — `\blabel\b` does not match `applabel`.)
     *
     * Stored lowercase: the checks below run over a lowercased statement.
     * `packageName`, `appLabel`, timestamps, buckets, scores and decision
     * sources are metadata this app produced about itself and stay freely
     * aggregable.
     */
    private val CONTENT_COLUMNS = setOf("title", "text", "senderkey", "contentshape", "label")

    private val FORBIDDEN = listOf(
        "insert", "update", "delete", "drop", "alter", "create", "replace",
        "pragma", "attach", "detach", "vacuum", "reindex", "trigger",
        "sqlite_master", "sqlite_temp_master", "sqlite_schema", "load_extension",
    )
    private val FORBIDDEN_PATTERNS = FORBIDDEN.map { it to Regex("""\b${Regex.escape(it)}\b""") }

    // A compound SELECT (UNION[ALL]/INTERSECT/EXCEPT) has more than one
    // projection, and this validator only ever inspects the first branch's
    // projection for a leaking star -- the Ask tab has no need to emit one,
    // so the whole class is refused rather than taught to the parser.
    private val COMPOUND_KEYWORDS = listOf("union", "intersect", "except")
    private val COMPOUND_PATTERNS = COMPOUND_KEYWORDS.map { it to Regex("""\b${Regex.escape(it)}\b""") }

    private val QUOTE_CHARS = charArrayOf('"', '`', '[', ']')

    private val SELECT_START = Regex("""^select\b""", RegexOption.IGNORE_CASE)
    private val FROM_OR_JOIN = Regex("""\b(?:from|join)\s+([a-z_][a-z0-9_]*)""", RegexOption.IGNORE_CASE)
    private val FROM_OR_JOIN_PAREN = Regex("""\b(?:from|join)\s*\(""", RegexOption.IGNORE_CASE)
    private val FROM_KEYWORD = Regex("""\bfrom\b""", RegexOption.IGNORE_CASE)
    private val CLAUSE_STOP_WORDS = setOf("where", "group", "having", "order", "limit")
    private val FENCE = Regex("""^```(?:sql)?\s*|\s*```$""", RegexOption.IGNORE_CASE)

    // Exactly one LIMIT is tolerated, and it must be the final clause of the
    // statement: `LIMIT <n>` optionally followed by `OFFSET <n>`. Anchoring to
    // the end of the string rules out `LIMIT 1, 100000` (SQLite's
    // offset,count form — the number that actually bounds the result set is
    // the *second* one) and `LIMIT 5*1000` (an expression, not a bare
    // integer), both of which a non-anchored "first digits after limit"
    // capture would misread as the small, safe-looking number.
    private val LIMIT_KEYWORD = Regex("""\blimit\b""", RegexOption.IGNORE_CASE)
    private val LIMIT_CLAUSE = Regex(
        """\blimit\s+(\d+)\s*(?:offset\s+\d+\s*)?$""",
        setOf(RegexOption.IGNORE_CASE),
    )

    // Quoted string literals can contain arbitrary text ('com.title.app') that
    // must not be mistaken for a keyword or column reference. Blank them out
    // (preserving length, so other offsets/regexes are unaffected) before any
    // keyword or column-name check.
    private val STRING_LITERAL = Regex("""'[^']*'""")
    private fun maskLiterals(s: String) = STRING_LITERAL.replace(s) { " ".repeat(it.value.length) }

    private fun hasUnbalancedParens(text: String): Boolean {
        var depth = 0
        for (c in text) {
            when (c) {
                '(' -> depth++
                ')' -> {
                    depth--
                    if (depth < 0) return true
                }
            }
        }
        return depth != 0
    }

    // A leading DISTINCT/ALL quantifier is a SELECT-level modifier, not part
    // of any projected column; it must be stripped before the projection is
    // inspected for a star, or `SELECT DISTINCT *` would fail to be
    // recognised as `SELECT *` in disguise.
    private val QUANTIFIER_PREFIX = Regex("""^\s*(?:distinct|all)\b\s*""", RegexOption.IGNORE_CASE)

    // A single top-level projected item is a content-column leak only if,
    // once trimmed, it is *exactly* a bare or table-qualified star -- `*`,
    // `n.*`, or `n .*` with arbitrary space around the dot. `COUNT(*)` never
    // matches this because of the surrounding `count(` / `)`.
    private val STAR_ITEM = Regex("""^(?:[a-z_][a-z0-9_]*\s*\.\s*)?\*$""")

    // Splits on commas that sit at paren depth 0 relative to the start of the
    // given string -- i.e. it will not split inside `(SELECT COUNT(*) FROM t)`
    // or an `IN (a, b)` list. Callers only ever pass a substring already known
    // to be internally balanced (the whole statement passed
    // hasUnbalancedParens first), so this never needs to handle negative depth.
    private fun splitTopLevel(s: String): List<String> {
        val items = mutableListOf<String>()
        var depth = 0
        var start = 0
        for (idx in s.indices) {
            when (s[idx]) {
                '(' -> depth++
                ')' -> depth--
                ',' -> if (depth == 0) {
                    items.add(s.substring(start, idx))
                    start = idx + 1
                }
            }
        }
        items.add(s.substring(start))
        return items
    }

    /**
     * SQLite's own definition of an identifier character — which is what
     * decides whether a keyword this scanner thinks it sees is really a
     * keyword, or merely part of a longer identifier.
     *
     * ASCII letters, digits, `_`, `$`, and every character at or above
     * U+0080: SQLite's tokeniser treats any byte with the high bit set as an
     * identifier byte, so `having«` is one identifier to it. Established by
     * brute-forcing U+0001..U+02FF through a real SQLite (3.51) in both
     * leading and trailing position, not by reading the source.
     *
     * `Char.isLetterOrDigit()` was the wrong question and was a bypass: it is
     * false for `«`, `°`, `$` and NBSP, all of which SQLite accepts inside an
     * identifier. So `FROM notifications having«, android_metadata` read as
     * a `having` stop word here — ending [hasCommaInAnyFromClause]'s scan and
     * hiding the comma join behind it — while SQLite read `having«` as an
     * ordinary alias and executed the join. Counting *more* things as
     * identifier characters can only shorten the set of keywords recognised,
     * and every caller of [keywordAt] fails towards a rejection when a
     * keyword is not recognised, so this direction cannot loosen the gate.
     */
    private fun isIdentifierChar(c: Char): Boolean =
        c in 'a'..'z' || c in 'A'..'Z' || c in '0'..'9' ||
            c == '_' || c == '$' || c.code >= 0x80

    private fun boundaryBefore(text: String, pos: Int) =
        pos <= 0 || !isIdentifierChar(text[pos - 1])
    private fun boundaryAfter(text: String, pos: Int) =
        pos >= text.length || !isIdentifierChar(text[pos])

    private fun asciiLower(c: Char) = if (c in 'A'..'Z') c + 32 else c

    /**
     * Case-insensitive comparison folding **only** `A-Z`, matching SQLite's
     * own keyword matching exactly.
     *
     * This is a fix for a real bypass, not a style preference. `lowercase()`
     * is not a case-folding normaliser, and the JVM's
     * `regionMatches(ignoreCase = true)` compares through
     * `toUpperCase`/`toLowerCase`, under which exactly three non-ASCII
     * characters collide with an ASCII letter: U+0130 and U+0131 with `i`,
     * U+017F with `s`, U+212A with `k` (brute-forced over U+0080..U+FFFF).
     * Two of those letters appear in keywords this file matches — `having`
     * and `limit` carry `i`, `select` carries `s` — so
     * `SELECT locale FROM notifications havıng, android_metadata LIMIT 1`
     * matched the `having` stop word, ended that occurrence's clause scan
     * early, and hid the comma join that follows it. SQLite, which folds only
     * ASCII, read `havıng` as a plain alias and returned the unlisted
     * table's row. Matching *more* stop words than SQLite recognises is the
     * one direction in which [hasCommaInAnyFromClause] fails open.
     *
     * Folding ASCII (rather than dropping case-insensitivity altogether) is
     * what is wanted, because this method must still work on text that has
     * *not* been lowercased: RawQueryDao shares [parenGroupIsSubquery] and
     * deliberately does not lowercase, since `lowercase()` is not
     * length-preserving for all of Unicode (U+0130 lowercases to two
     * characters) and the paren walk is index-based. An earlier comment here
     * claimed the ignore-case flag was "a no-op for every in-file caller,
     * which all pass lowercased text"; that was false for exactly this reason
     * — lowercasing does not remove U+0131.
     */
    private fun asciiEqualsIgnoreCase(text: String, pos: Int, word: String): Boolean {
        for (k in word.indices) {
            if (asciiLower(text[pos + k]) != asciiLower(word[k])) return false
        }
        return true
    }

    private fun keywordAt(text: String, pos: Int, word: String) =
        pos + word.length <= text.length &&
            asciiEqualsIgnoreCase(text, pos, word) &&
            boundaryBefore(text, pos) &&
            boundaryAfter(text, pos + word.length)

    /**
     * The projection: the raw text between `select` and the statement's
     * *top-level* `from` — the one that actually determines what the outer
     * SELECT reads, as opposed to one nested inside a parenthesised
     * subquery embedded in the projection itself (depth > 0), which must be
     * skipped when locating this boundary. Returns `null` if no top-level
     * FROM is found, or if depth ever goes negative during the scan (which
     * should not happen once [hasUnbalancedParens] has already passed on
     * the whole statement, but is treated as a hard parse failure rather
     * than continuing with a depth counter that can no longer be trusted).
     */
    private fun findTopLevelProjection(masked: String): String? {
        val selectEnd = SELECT_START.find(masked)?.range?.last?.plus(1) ?: return null
        val n = masked.length

        var depth = 0
        var j = selectEnd
        while (j < n) {
            when (masked[j]) {
                '(' -> depth++
                ')' -> {
                    depth--
                    if (depth < 0) return null
                }
            }
            if (depth == 0 && keywordAt(masked, j, "from")) {
                return masked.substring(selectEnd, j)
            }
            j++
        }
        return null
    }

    /**
     * A comma join can hide inside *any* `FROM` in the statement, not just
     * the outermost one — including one nested inside a WHERE/HAVING
     * subquery, or one nested inside a subquery embedded in the projection.
     * Every occurrence of the `from` keyword gets its own independent scan
     * of its own local table clause, starting its own depth counter at 0
     * from right after that particular `from`: the scan for one occurrence
     * ends either at a stop word (where/group/order/limit) found at that
     * occurrence's own depth 0, or when depth goes negative (meaning the
     * scan has exited back through the paren that was enclosing this
     * particular `from`, i.e. reached the end of its own clause). A comma
     * found at depth 0 during any one occurrence's scan is a comma join,
     * regardless of where in the statement that `from` sits.
     */
    private fun hasCommaInAnyFromClause(masked: String): Boolean {
        for (match in FROM_KEYWORD.findAll(masked)) {
            var depth = 0
            var i = match.range.last + 1
            while (i < masked.length) {
                val c = masked[i]
                when (c) {
                    '(' -> depth++
                    ')' -> {
                        depth--
                        if (depth < 0) break
                    }
                }
                if (depth == 0) {
                    if (c == ',') return true
                    if (CLAUSE_STOP_WORDS.any { keywordAt(masked, i, it) }) break
                }
                i++
            }
        }
        return false
    }

    /**
     * SQLite's grammar allows `table-or-subquery := ( join-clause )`, and `,`
     * is itself a join operator — so `JOIN (notifications, android_metadata)`
     * is a parenthesised join clause naming a second, entirely unvetted
     * table, and neither the comma-join scan above (which only looks inside
     * a `FROM` keyword's own clause) nor [FROM_OR_JOIN] (which requires a
     * bare identifier immediately after `from`/`join`, not a `(`) ever sees
     * it. Rather than teach either of those checks about this grammar rule,
     * a `(` directly following `from`/`join` is only ever permitted when it
     * opens an ordinary subquery — see [parenGroupIsSubquery]. Anything else
     * (a bare table list, an alias, another join clause) is rejected outright.
     */
    private fun hasNonSubqueryParenAfterFromOrJoin(masked: String): Boolean =
        FROM_OR_JOIN_PAREN.findAll(masked).any { !parenGroupIsSubquery(masked, it.range.last) }

    /**
     * Is the group opened by the `(` at [openParenIdx] an ordinary subquery?
     *
     * Yes if its first non-whitespace token is `select`. A group whose first
     * token is instead another `(` is a *wrapping* group — `((SELECT …))`,
     * the redundantly-parenthesised subquery form — and is walked into. But a
     * wrapping group introduces no table of its own, so the only thing a
     * comma at that group's own top level can be doing is joining something
     * else to the group it wraps: `((SELECT 1), unvetted_table)` is a
     * parenthesised join clause wearing a subquery's hat. An earlier revision
     * skipped nested `(` unconditionally and then looked for `select`, which
     * that shape satisfies — the `select` it found belonged to the inner
     * group, not to the outer one that actually holds the join. So every
     * wrapping group traversed on the way in must itself be comma-free; only
     * the innermost, `select`-opening group may contain commas, since those
     * are its own projection's.
     *
     * Iterative rather than recursive: the nesting depth is attacker-chosen.
     *
     * SHARED, deliberately. [com.anuj.notificationfirewall.data.db.dao.RawQueryDao]
     * needs exactly this question when it decides whether a `FROM (`/`JOIN (`
     * group may bind an alias, and a review round found that its own copy of
     * this walk -- which had dropped the [hasTopLevelCommaInGroup] call above
     * -- accepted `FROM ((SELECT 1), android_metadata q) q` and bound `q`,
     * re-opening the very bypass the comma check was added to close. The two
     * gates stay independent in *what* they check -- the validator reads the
     * statement, the DAO reads SQLite's own query plan -- but this is a purely
     * syntactic utility with a hard-won correct implementation, and there must
     * be exactly one of it. Do not copy this method; call it.
     */
    internal fun parenGroupIsSubquery(masked: String, openParenIdx: Int): Boolean {
        var open = openParenIdx
        while (true) {
            var idx = open + 1
            while (idx < masked.length && masked[idx].isWhitespace()) idx++
            if (idx >= masked.length) return false
            if (masked[idx] != '(') return keywordAt(masked, idx, "select")
            if (hasTopLevelCommaInGroup(masked, open)) return false
            open = idx
        }
    }

    /**
     * Does the group opened by the `(` at [openParenIdx] contain a comma at
     * its own top level — i.e. one not nested inside a further paren pair?
     * The scan stops at the `)` that closes this group.
     */
    private fun hasTopLevelCommaInGroup(masked: String, openParenIdx: Int): Boolean {
        var depth = 0
        var i = openParenIdx + 1
        while (i < masked.length) {
            when (masked[i]) {
                '(' -> depth++
                ')' -> {
                    if (depth == 0) return false
                    depth--
                }
                ',' -> if (depth == 0) return true
            }
            i++
        }
        return false
    }

    fun validate(raw: String, allowContent: Boolean): SqlVerdict {
        val sql = raw.trim().replace(FENCE, "").trim().removeSuffix(";").trim()

        if (sql.isEmpty()) return SqlVerdict.Rejected("Empty statement")

        // Comments can hide a second statement from a naive split, and nothing
        // legitimate here needs them.
        if (sql.contains("--") || sql.contains("/*")) {
            return SqlVerdict.Rejected("Comments are not permitted")
        }
        if (sql.contains(";")) {
            return SqlVerdict.Rejected("Only a single statement is permitted")
        }
        if (sql.any { it in QUOTE_CHARS }) {
            return SqlVerdict.Rejected("Quoted or bracketed identifiers (\", `, [, ]) are not permitted")
        }

        val lower = sql.lowercase()
        val masked = maskLiterals(lower)

        if (hasUnbalancedParens(masked)) {
            return SqlVerdict.Rejected("Unbalanced parentheses")
        }

        if (!SELECT_START.containsMatchIn(lower)) {
            return SqlVerdict.Rejected("Only SELECT statements are permitted")
        }
        FORBIDDEN_PATTERNS.firstOrNull { (_, pattern) -> pattern.containsMatchIn(masked) }
            ?.let { (word, _) -> return SqlVerdict.Rejected("Forbidden keyword: $word") }

        COMPOUND_PATTERNS.firstOrNull { (_, pattern) -> pattern.containsMatchIn(masked) }
            ?.let { (word, _) ->
                return SqlVerdict.Rejected("Compound statements ($word) are not supported; only a single SELECT is permitted")
            }

        if (hasCommaInAnyFromClause(masked)) {
            return SqlVerdict.Rejected("Comma joins are not supported; use JOIN")
        }

        if (hasNonSubqueryParenAfterFromOrJoin(masked)) {
            return SqlVerdict.Rejected("A parenthesised join clause is not supported; only a subquery is permitted after FROM/JOIN")
        }

        val tables = FROM_OR_JOIN.findAll(masked).map { it.groupValues[1] }.toSet()
        if (tables.isEmpty()) return SqlVerdict.Rejected("No table referenced")
        (tables - KNOWN_TABLES).firstOrNull()
            ?.let { return SqlVerdict.Rejected("Unknown table: $it") }

        if (!allowContent) {
            val projection = findTopLevelProjection(masked)
                ?: return SqlVerdict.Rejected("Could not determine the SELECT projection")
            val body = QUANTIFIER_PREFIX.replaceFirst(projection, "")
            val isStarProjection = splitTopLevel(body).any { STAR_ITEM.matches(it.trim()) }
            if (isStarProjection) {
                return SqlVerdict.Rejected("SELECT * would expose notification content")
            }
            CONTENT_COLUMNS.firstOrNull { Regex("""\b$it\b""").containsMatchIn(masked) }
                ?.let { return SqlVerdict.Rejected("Column '$it' derives from notification content") }
        }

        if (LIMIT_KEYWORD.findAll(masked).count() != 1) {
            return SqlVerdict.Rejected("Exactly one LIMIT clause is required")
        }
        val limitMatch = LIMIT_CLAUSE.find(masked)
            ?: return SqlVerdict.Rejected("LIMIT must be the final clause, as LIMIT <n> optionally followed by OFFSET <n>")
        val limit = limitMatch.groupValues[1].toIntOrNull()
            ?: return SqlVerdict.Rejected("A LIMIT is required")
        if (limit > MAX_LIMIT) return SqlVerdict.Rejected("LIMIT must be at most $MAX_LIMIT")

        return SqlVerdict.Allowed(sql)
    }
}
